### ISSUE TITLE
GitLab repo format errors for datetime fields

### ISSUE THREAD

**Issue by coni2k** [ossf/criticality_score#64]
When I run the script against a GitLab repository, I get format errors for datetime fields (due to having different regional settings?). Let me know if you need more info on this.

```shell
> python -u -m criticality_score.run --repo gitlab.com/gitlab-org/gitlab

Exception in thread Thread-1:
Traceback (most recent call last):
  File "\Python\Python36-32\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "\Python\Python36-32\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "\ossf\criticality_score\criticality_score\run.py", line 405, in _worker
    return_dict[param] = getattr(repo, param)
  File "\ossf\criticality_score\criticality_score\run.py", line 292, in created_since
    creation_time = self._date_from_string(self._repo.created_at)
  File "\ossf\criticality_score\criticality_score\run.py", line 275, in _date_from_string
    "%Y-%m-%dT%H:%M:%S.%f%z")
  File "\Python\Python36-32\lib\_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "\Python\Python36-32\lib\_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '2015-05-20T10:47:11.949Z' does not match format '%Y-%m-%dT%H:%M:%S.%f%z'

Exception in thread Thread-2:
Traceback (most recent call last):
  File "\Python\Python36-32\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "\Python\Python36-32\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "\ossf\criticality_score\criticality_score\run.py", line 405, in _worker
    return_dict[param] = getattr(repo, param)
  File "\ossf\criticality_score\criticality_score\run.py", line 308, in updated_since
    last_commit.created_at)
  File "\ossf\criticality_score\criticality_score\run.py", line 275, in _date_from_string
    "%Y-%m-%dT%H:%M:%S.%f%z")
  File "\Python\Python36-32\lib\_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "\Python\Python36-32\lib\_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '2021-01-07T17:46:27.000+00:00' does not match format '%Y-%m-%dT%H:%M:%S.%f%z'

Exception in thread Thread-6:
Traceback (most recent call last):
  File "\Python\Python36-32\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "\Python\Python36-32\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "\ossf\criticality_score\criticality_score\run.py", line 405, in _worker
    return_dict[param] = getattr(repo, param)
  File "\ossf\criticality_score\criticality_score\run.py", line 334, in recent_releases_count
    release_time = self._date_from_string(release.released_at)
  File "\ossf\criticality_score\criticality_score\run.py", line 275, in _date_from_string
    "%Y-%m-%dT%H:%M:%S.%f%z")
  File "\Python\Python36-32\lib\_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "\Python\Python36-32\lib\_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '2020-12-22T00:00:00.000Z' does not match format '%Y-%m-%dT%H:%M:%S.%f%z'
```

**Comment by inferno-chromium** [comment]
Which python3 version are you on, it works for me on 3.8.6

**Comment by coni2k** [comment]
Indeed, python version was the problem.
I was using 3.6. The problem is gone after upgrading to 3.9.1 👍

```shell
> python
Python 3.9.1 (tags/v3.9.1:1e5d33e, Dec  7 2020, 17:08:21) [MSC v.1927 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import datetime
>>> datetime.datetime.strptime('2015-05-20T10:47:11.949Z', "%Y-%m-%dT%H:%M:%S.%f%z")
datetime.datetime(2015, 5, 20, 10, 47, 11, 949000, tzinfo=datetime.timezone.utc)
>>> datetime.datetime.strptime('2021-01-07T17:46:27.000+00:00', "%Y-%m-%dT%H:%M:%S.%f%z")
datetime.datetime(2021, 1, 7, 17, 46, 27, tzinfo=datetime.timezone.utc)
>>> datetime.datetime.strptime('2020-12-22T00:00:00.000Z', "%Y-%m-%dT%H:%M:%S.%f%z")
datetime.datetime(2020, 12, 22, 0, 0, tzinfo=datetime.timezone.utc)
```
