### ISSUE TITLE
KeyError: 'comment_frequency'

### ISSUE THREAD

**Issue by strus38** [ossf/criticality_score#94]
Hi

Trying to run the sample command just after a fresh installation, here is the error I got:
```
root@DESKTOP-NGTHQJ9:~# criticality_score --repo github.com/kubernetes/kubernetes
Exception in thread Thread-9:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.6/dist-packages/criticality_score/run.py", line 405, in _worker
    return_dict[param] = getattr(repo, param)
  File "/usr/local/lib/python3.6/dist-packages/criticality_score/run.py", line 266, in comment_frequency
    since=issues_since_time).totalCount
  File "/usr/local/lib/python3.6/dist-packages/github/PaginatedList.py", line 150, in totalCount
    "GET", self.__firstUrl, parameters=params, headers=self.__headers
  File "/usr/local/lib/python3.6/dist-packages/github/Requester.py", line 355, in requestJsonAndCheck
    verb, url, parameters, headers, input, self.__customConnection(url)
  File "/usr/local/lib/python3.6/dist-packages/github/Requester.py", line 378, in __check
    raise self.__createException(status, responseHeaders, output)
github.GithubException.GithubException: 502 {"message": "Server Error"}

Traceback (most recent call last):
  File "/usr/local/bin/criticality_score", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/criticality_score/run.py", line 555, in main
    output = get_repository_stats(repo, args.params)
  File "/usr/local/lib/python3.6/dist-packages/criticality_score/run.py", line 424, in get_repository_stats
    result_dict[param] = return_dict[param]
KeyError: 'comment_frequency'
```

Any idea what is going wrong?

**Comment by calebbrown** [comment]
While re-implementing the project in Go I discovered that this error is caused by too many comments.

To solve this issue if we detect a 502 during a query for comment count we revert to a frequency of "2" ([code ref]( https://github.com/ossf/criticality_score/blob/e2ee6f195528820a0d9dc8117d2e20f3a3fcfdd8/internal/collector/github/legacy/issues.go#L70))

"2" is somewhat arbitrary and was based on the general distribution of frequencies across all the repos collected.
